### ISSUE TITLE
Añadir aprovisionamiento con Ansible. 

### ISSUE THREAD

**Issue by joseangeldiazg** [joseangeldiazg/MII-CloudComputing#5]
Añadir los ficheros y configuraciones necesarias para promocionar la aplicación usando Ansible.

**Comment by AythaE** [comment]
Comprobado correcto funcionamiento en AWS con Ubuntu 14.04

![Imagen provisionamiento]( https://raw.githubusercontent.com/AythaE/DeFesti/gh-pages/images/Ejecucion%20ansible%20joseangeldiazg.png "Imagen provisionamiento")
