### ISSUE TITLE
Añadir aprovisionamiento con Chef-Solo. 

### ISSUE THREAD

**Issue by joseangeldiazg** [joseangeldiazg/MII-CloudComputing#6]
Añadiremos otra forma de aprovisionar la aplicación usando chef-solo como herramienta.

**Comment by AythaE** [comment]
Provisionamiento probado correctamente en AWS con Ubuntu 14.04

![Imagen provisionamiento](https://raw.githubusercontent.com/AythaE/DeFesti/gh-pages/images/Ejecucion%20chef%20joseangeldiazg.png "Imagen provisionamiento")
